# Generated by Django 2.2 on 2020-09-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(db_index=True, max_length=200)),
                ('model', models.SlugField(max_length=200)),
                ('vin_number', models.CharField(db_index=True, max_length=200)),
                ('purchase_date', models.DateTimeField()),
                ('last_service', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('make',),
                'index_together': {('model',)},
            },
        ),
    ]
