# Generated by Django 2.2 on 2020-09-09 03:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='owner',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
